devtools::load_all()
access_trace_reset()
devtools::load_all()
access_trace_add("bru_obs", package = c("inlabru"))
access_trace_add("bru_comp", package = c("inlabru"))
access_trace_add("bru_used", package = c("inlabru"))
access_trace_add("bru", package = c("inlabru"))
access_trace_add("bru_obs", package = c("inlabru"))
access_trace_add("bru_pred_expr", package = c("inlabru"))
access_trace_add("bru_input", package = c("inlabru"))
access_trace_add("bru_mapper", package = c("inlabru"))

devtools::document()
devtools::load_all()
