// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// inlabru_group_cv_block_conversion
Rcpp::List inlabru_group_cv_block_conversion(Rcpp::IntegerVector block, int max_block, bool per_node);
RcppExport SEXP _inlabru_inlabru_group_cv_block_conversion(SEXP blockSEXP, SEXP max_blockSEXP, SEXP per_nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type block(blockSEXP);
    Rcpp::traits::input_parameter< int >::type max_block(max_blockSEXP);
    Rcpp::traits::input_parameter< bool >::type per_node(per_nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(inlabru_group_cv_block_conversion(block, max_block, per_node));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_inlabru_inlabru_group_cv_block_conversion", (DL_FUNC) &_inlabru_inlabru_group_cv_block_conversion, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_inlabru(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
