access_trace <- function(name) {
  method <- fmesher::fm_caller_name(-1)
  access_method_ <- list(
    "^\\$<-" = "$<-",
    "^\\$" = "$",
    "^\\[\\[<-" = "[[<-",
    "^\\[\\[" = "[[",
    "^\\[<-" = "[<-",
    "^\\[" = "["
  )
  access_method <- NA_character_
  for (pattern in names(access_method_)) {
    if (grepl(pattern, method)) {
      access_method <- access_method_[[pattern]]
      break
    }
  }
  method_text_ <-
    list(
      "$<-" = "\\$<-",
      "$" = "\\$",
      "[[<-" = "\\[\\[<-",
      "[[" = "\\[\\[",
      "[<-" = "\\[<-",
      "[" = "\\["
    )
  method_text <- if (access_method %in% names(method_text_)) {
    method_text_[[access_method]]
  } else {
    ""
  }
  open_text_ <- list(
    "$<-" = "$",
    "$" = "$",
    "[[<-" = "[['",
    "[[" = "[['",
    "[<-" = "['",
    "[" = "['"
  )
  open_text <- if (access_method %in% names(open_text_)) {
    open_text_[[access_method]]
  } else {
    ""
  }
  close_text_ <- list(
    "$<-" = " <-",
    "$" = "",
    "[[<-" = "']] <-",
    "[[" = "']]",
    "[<-" = "'] <-",
    "[" = "']"
  )
  close_text <- if (access_method %in% names(close_text_)) {
    close_text_[[access_method]]
  } else {
    ""
  }
  class_name <- sub(paste0("^", method_text, "\\."), "", method)
  idx <- -3
  caller <- fmesher::fm_caller_name(idx)
  if (identical(caller, "FUN")) {
    idx <- idx - 1L
    cal <- fmesher::fm_caller_name(idx)
    caller <- paste0(cal, ":FUN")
  }
  idx <- idx - 1L
  cal <- fmesher::fm_caller_name(idx)
  caller <- paste0(cal, ":", caller)
  print(glue::glue("{caller}: {class_name}{open_text}{name}{close_text}"))
}



access_trace_reset <- function(file = "R/access_trace_methods.R") {
  write(
    c(
      "# This file is auto-generated by access_trace_reset/add() calls.",
      "# Do not edit!"
    ),
    file = file,
    append = FALSE,
    sep = ""
  )
  invisible()
}


access_trace_add <- function(
    class_name,
    method_names = c("$", "[[", "[", "$<-", "[[<-", "[<-"),
    file = "R/access_trace_methods.R") {
  write(
    c("", glue::glue("# Class {class_name} ####"), ""),
    file = file,
    append = TRUE,
    sep = ""
  )
  for (method_name in method_names) {
    if (method_name %in% c("$<-", "[[<-", "[<-")) {
      extra_arguments <- ", value"
    } else {
      extra_arguments <- ""
    }
    code <- c(glue::glue(
      "#' @export
       #'
       `{method_name}.{class_name}` <- function(x, name{extra_arguments}) {{
         access_trace(name)
         NextMethod()
       }}"
    ), "")
    write(
      code,
      file = file,
      append = TRUE,
      sep = ""
    )
  }
  invisible()
}
