#' @import fmesher
#'
#' @export "fm_crs_oblique<-"
#' @export "fm_ellipsoid_radius<-"
#' @export "fm_length_unit<-"
#' @export fm_CRS
#' @export fm_CRS_as_list
#' @export fm_CRSargs
#' @export fm_CRSargs_as_list
#' @export fm_as_inla_mesh
#' @export fm_as_inla_mesh_segment
#' @export fm_as_sfc
#' @export fm_as_sp_crs
#' @export fm_contains
#' @export fm_cprod
#' @export fm_crs
#' @export fm_crs_get_ellipsoid_radius
#' @export fm_crs_get_lengthunit
#' @export fm_crs_get_wkt
#' @export fm_crs_is_geocent
#' @export fm_crs_oblique
#' @export fm_crs_set_ellipsoid_radius
#' @export fm_crs_set_lengthunit
#' @export fm_ellipsoid_radius
#' @export fm_evaluate
#' @export fm_evaluator
#' @export fm_evaluator_inla_mesh
#' @export fm_evaluator_inla_mesh_1d
#' @export fm_evaluator_lattice
#' @export fm_has_PROJ6
#' @export fm_identical_CRS
#' @export fm_int
#' @export fm_int_inla_mesh
#' @export fm_int_multi_sampler
#' @export fm_length_unit
#' @export fm_list_as_CRS
#' @export fm_pixels
#' @export fm_proj4string
#' @export fm_sp2segment
#' @export fm_spTransform
#' @export fm_sp_get_crs
#' @export fm_transform
#' @export fm_wkt
#' @export fm_wkt_as_wkt_tree
#' @export fm_wkt_get_ellipsoid_radius
#' @export fm_wkt_get_lengthunit
#' @export fm_wkt_is_geocent
#' @export fm_wkt_predef
#' @export fm_wkt_set_ellipsoid_radius
#' @export fm_wkt_set_lengthunit
#' @export fm_wkt_tree_as_wkt
#' @export fm_wkt_tree_get_item
#' @export fm_wkt_tree_set_item
#' @export fm_wkt_unit_params

NULL
