#' inlabru
#' 
#' Inference for spatial point process data that arise from surveys that do not necessarily 
#' detect all points generated by the process. This includes, but is not limeted to, data that arise 
#' from plot sampling surveys and distance sampling surveys.
#' 
#' @details 
#'
#' inla bru facilitates Bayesian spatial modeling using integrated nested Laplace approximations. It
#' is heavily based on R-inla (\url{http://www.r-inla.org}) but adds additional modeling abilities.
#' Tutorials and more information can be found at \url{https://fbachl.github.io/inlabru/} and
#' soon also at \url{http://inlabru.r-inla.org/}.
#' 
#' @aliases inlabru
#' @author Fabian E. Bachl <\email{f.e.bachl@@bath.ac.uk}>
#' @name inlabru
NULL