#' Striped dolphin ETP survey data
#' 
#' A data set containing short beaked dolphin sightings, transects data
#' and a mesh modeling the survey area. The data is generated by 
#' \code{\link{io_strdolphin.pkgdata.save}}, which loads the raw data
#' using \code{\link{io_strdolphin.pkgdata.load}}. The components of the data
#' set are accessible via \code{\link{io_whales.sightings}}, 
#' \code{\link{io_strdolphin.transects}} and \code{\link{io_strdolphin.mesh}}.
#' Additinal data which is not included in the package can be loaded via 
#' \code{\link{io_strdolphin.boundary}} as well as 
#' \code{\link{io_strdolphin.pkgdata.coast}}
#' 
#' @source \url{http://www.creem.st-andrews.ac.uk:8082/ESSMod/case-studies}
#' @examples \\donttest{ data(strdolphin) ; plot(strdolphin)}
#' @name strdolphin
NULL
