#' Whale survey data.
#' 
#' A data set containing whale sightings, transects data
#' and a mesh modeling the survey area. The data is generated by 
#' \code{\link{io_whales.pkgdata.save}}, which loads the raw data
#' using \code{\link{io_whales.pkgdata.load}}. The components of the data
#' set are accessible via \code{\link{io_whales.sightings}}, 
#' \code{\link{io_whales.transects}} and \code{\link{io_whales.mesh}}.
#' Additinal data which is not included in the package can be loaded via 
#' \code{\link{io_whales.boundary}} as well as 
#' \code{\link{io_whales.pkgdata.coast}}
#' 
#' @format \code{whales} is a data frame with the following fields:
#'  \describe{ 
#'   \item{sighting}{A
#'   list of whale sightings: latitude and longitude of ship position, distance
#'   of whales from observer} 
#'   \item{transect}{A list of transect segments} 
#'   \item{mesh}{An INLA mesh object modeling the survey area.} }
#' @source \url{http://www.creem.st-andrews.ac.uk:8082/ESSMod/case-studies}
#' @examples \\donttest{ data(whales) ; plot(whales$mesh)}
#' @name whales
NULL


#' Plot whales data
#'
#' @aliases plot.whales
#' @export
#' @examples \\dontrun{data(whales); plot(whales)}
#' @author Fabian E. Bachl <\email{f.e.bachl@@bath.ac.uk}>
#' 
plot.whales = function(...){ plot.dsdata(...) }
