# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - devel
      - feature/*
  pull_request:
    branches:
      - devel
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs on devel
    concurrency:
      group: pkgdown-${{ (github.event_name != 'pull_request' && github.ref_name == 'devel') || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: "release"
          extra-repositories: 'https://inla.r-inla-download.org/R/testing https://inlabru-org.r-universe.dev'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            local::.
            any::RColorBrewer
            any::ggplot2
            any::dplyr
            any::lwgeom
            any::tmaptools
            any::patchwork
            any::raster
          needs: website

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      # https://mxschmitt.github.io/action-tmate/
      - name: Setup tmate debugging session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Mermaid update
        run: |
          source("vignettes/articles/mermaid_updater.R")
        shell: Rscript {0}

      - name: Fix temporary out-of-sync binary packages
        run: |
          install.packages("MatrixModels", repos = "https://cloud.r-project.org", type = "source")
        shell: Rscript {0}

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE)
        shell: Rscript {0}

      - name: Upload website for deployment 🚀
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'devel' }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./docs
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: pkgdown
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'devel' }}
        uses: actions/configure-pages@v6

      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'devel' }}
        uses: actions/deploy-pages@v5


