# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - devel
      - stable
      - release/*
      - feature/*
  pull_request:
    branches:
      - devel
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: macos-latest, r: 'devel', http-user-agent: 'release'}
          - {os: macos-latest, r: 'release'}
          - {os: macos-latest, r: 'oldrel-1'}
#          - {os: windows-latest, r: 'devel', http-user-agent: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel-1'}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel-1'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: 'https://inla.r-inla-download.org/R/testing https://inlabru-org.r-universe.dev'

      - name: Install system dependencies on MacOS (X11, gdal)
        if: runner.os == 'macOS'
        run: |
          brew install libsm
          brew install libxrender
          brew install cairo
          brew install --cask xquartz
          brew install pkg-config
          brew install udunits
          brew install gdal
#          brew install proj@9
#          brew install gsl

      - name: Install system dependencies on Linux (GL)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && sudo apt-get install -y libglu1-mesa-dev

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      # https://mxschmitt.github.io/action-tmate/
      - name: Setup tmate debugging session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: |
             rcmdcheck
             Cairo
             remotes
             stars=?ignore
             starsdata=?ignore

#      - name: Fix temporary out-of-sync binary packages
#        run: |
#          install.packages("MatrixModels", repos = "https://cloud.r-project.org", type = "source")
#        shell: Rscript {0}

      - name: Limit INLA version to 24.05.10 on old R version
        run: |
          if (getRversion() < "4.4.0") {
            remotes::install_version("INLA", version = "24.05.10", repos = "https://inla.r-inla-download.org/R/testing")
          }
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
          tryCatch({
          sf::sf_proj_info("have_datum_files")
          sf::sf_proj_info("proj")
          sf::sf_proj_info("ellps")
          sf::sf_proj_info("datum")
          sf::sf_proj_info("units")
          sf::sf_proj_info("path")
          }, warning = function(w) message(w), error = function(e) message(e))
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        with:
          args: 'c("--no-manual", "--as-cran")'
